const oneProduct = [
  {
    itemId: 29168217,
    partNum: 'BAS16VY,115',
    manufacturer: {
      mfrCd: 'NEXPERIA',
      mfrName: 'Nexperia',
    },
    desc: 'Rectifier Diode Switching 100V 0.2A 4ns Automotive 6-Pin TSSOP T/R',
    packageType: '',
    resources: [
      {
        type: 'datasheet',
        uri: 'https://static6.arrow.com/aropdfconversion/ba577f79e697550ac6892bd3c6fcd5a805e2800f/66239194956612bas16_ser.pdf',
      },
      {
        type: 'image_small',
        uri: 'https://static6.arrow.com/aropdfconversion/arrowimages/cead3dde56c2270c71894ea2eff724a40e604580/sot363_3d.jpg',
      },
      {
        type: 'image_large',
        uri: 'https://static6.arrow.com/aropdfconversion/arrowimages/7022de42b63189773742f15213a477d5fa6b5c52/sot363_3d.jpg',
      },
      {
        type: 'cloud_part_detail',
        uri: 'https://www.arrow.com/en/products/bas16vy115/nexperia',
      },
      {
        type: 'api_part_detail',
        uri: 'http://api.arrow.com/itemservice/v2/en/detail?mfrCd=NEXPERIA&partNum=BAS16VY115',
      },
      {
        type: 'part_detail',
        uri: 'http://api.arrow.com/itemservice/v2/en/detail?pkey=JwbjgOvnkHL_KWy7sW4q6I9ALCFucy6F1mkST_576Kg',
      },
    ],
    EnvData: {
      compliance: [
        {
          displayLabel: 'eurohs',
          displayValue: 'Compliant',
        },
        {
          displayLabel: 'cnrohs',
          displayValue: 'Compliant',
        },
      ],
    },
    InvOrg: {
      webSites: [
        {
          code: 'Verical.com',
          name: 'Verical.com',
          sources: [
            {
              currency: 'USD',
              sourceCd: 'VERICAL',
              displayName: 'Verical',
              sourceParts: [
                {
                  packSize: 1,
                  minimumOrderQuantity: 191,
                  sourcePartId: '32404324',
                  Prices: {
                    resaleList: [
                      {
                        displayPrice: '0.0377',
                        price: 0.0377,
                        minQty: 191,
                        maxQty: 249,
                        vipPrice: true,
                      },
                      {
                        displayPrice: '0.0352',
                        price: 0.0352,
                        minQty: 250,
                        maxQty: 499,
                        vipPrice: true,
                      },
                      {
                        displayPrice: '0.0327',
                        price: 0.0327,
                        minQty: 500,
                        maxQty: 999,
                        vipPrice: true,
                      },
                      {
                        displayPrice: '0.0301',
                        price: 0.0301,
                        minQty: 1000,
                        maxQty: 2999,
                        vipPrice: true,
                      },
                      {
                        displayPrice: '0.0295',
                        price: 0.0295,
                        minQty: 3000,
                        maxQty: 99999999,
                        vipPrice: true,
                      },
                    ],
                  },
                  Availability: [
                    {
                      fohQty: 16403,
                      availabilityCd: 'INSTK',
                      availabilityMessage: 'In Stock',
                      pipeline: [],
                    },
                  ],
                  customerSpecificPricing: [],
                  customerSpecificInventory: [],
                  dateCode: '1909',
                  resources: [
                    {
                      type: 'detail',
                      uri: 'https://www.verical.com/pd/nexperia-rectifier-BAS16VY-115-3235293',
                    },
                    {
                      type: 'add_to_cart',
                      uri: 'https://www.verical.com/pd/nexperia-rectifier-BAS16VY-115-3235293',
                    },
                  ],
                  inStock: true,
                  mfrLeadTime: 0,
                  tariffFlag: false,
                  shipsFrom: 'United States of America',
                  shipsIn: 'Ships today',
                  arrowLeadTime: '',
                  isNcnr: false,
                  isNpi: false,
                  productCode: 'BAS16VY115',
                  eccnCode: 'EAR99',
                  htsCode: '8541.10.00.80',
                  countryOfOrigin: 'MY',
                  containerType: '',
                },
                {
                  packSize: 3000,
                  minimumOrderQuantity: 3000,
                  sourcePartId: '53675853',
                  Prices: {
                    resaleList: [
                      {
                        displayPrice: '0.0323',
                        price: 0.0323,
                        minQty: 3000,
                        maxQty: 20999,
                        vipPrice: true,
                      },
                      {
                        displayPrice: '0.0317',
                        price: 0.0317,
                        minQty: 21000,
                        maxQty: 99999999,
                        vipPrice: true,
                      },
                    ],
                  },
                  Availability: [
                    {
                      fohQty: 90000,
                      availabilityCd: 'INSTK',
                      availabilityMessage: 'In Stock',
                      pipeline: [],
                    },
                  ],
                  customerSpecificPricing: [],
                  customerSpecificInventory: [],
                  dateCode: '2103',
                  resources: [
                    {
                      type: 'detail',
                      uri: 'https://www.verical.com/pd/nexperia-rectifier-BAS16VY-115-3235293',
                    },
                    {
                      type: 'add_to_cart',
                      uri: 'https://www.verical.com/pd/nexperia-rectifier-BAS16VY-115-3235293',
                    },
                  ],
                  inStock: true,
                  mfrLeadTime: 0,
                  tariffFlag: false,
                  shipsFrom: 'Netherlands',
                  shipsIn: 'Ships in 3 days ',
                  arrowLeadTime: '',
                  isNcnr: false,
                  isNpi: false,
                  productCode: 'BAS16VY115',
                  eccnCode: 'EAR99',
                  htsCode: '8541.10.00.80',
                  countryOfOrigin: 'MY',
                  containerType: '',
                },
                {
                  packSize: 3000,
                  minimumOrderQuantity: 3000,
                  sourcePartId: '53287321',
                  Prices: {
                    resaleList: [
                      {
                        displayPrice: '0.0289',
                        price: 0.0289,
                        minQty: 3000,
                        maxQty: 8999,
                        vipPrice: true,
                      },
                      {
                        displayPrice: '0.0283',
                        price: 0.0283,
                        minQty: 9000,
                        maxQty: 99999999,
                        vipPrice: true,
                      },
                    ],
                  },
                  Availability: [
                    {
                      fohQty: 42000,
                      availabilityCd: 'INSTK',
                      availabilityMessage: 'In Stock',
                      pipeline: [],
                    },
                  ],
                  customerSpecificPricing: [],
                  customerSpecificInventory: [],
                  dateCode: '1933',
                  resources: [
                    {
                      type: 'detail',
                      uri: 'https://www.verical.com/pd/nexperia-rectifier-BAS16VY-115-3235293',
                    },
                    {
                      type: 'add_to_cart',
                      uri: 'https://www.verical.com/pd/nexperia-rectifier-BAS16VY-115-3235293',
                    },
                  ],
                  inStock: true,
                  mfrLeadTime: 0,
                  tariffFlag: false,
                  shipsFrom: 'United States of America',
                  shipsIn: 'Ships today',
                  arrowLeadTime: '',
                  isNcnr: false,
                  isNpi: false,
                  productCode: 'BAS16VY115',
                  eccnCode: 'EAR99',
                  htsCode: '8541.10.00.80',
                  countryOfOrigin: 'MY',
                  containerType: '',
                },
                {
                  packSize: 3000,
                  minimumOrderQuantity: 3000,
                  sourcePartId: '53408271',
                  Prices: {
                    resaleList: [
                      {
                        displayPrice: '0.0441',
                        price: 0.0441,
                        minQty: 3000,
                        maxQty: 99999999,
                        vipPrice: true,
                      },
                    ],
                  },
                  Availability: [
                    {
                      fohQty: 132000,
                      availabilityCd: 'INSTK',
                      availabilityMessage: 'In Stock',
                      pipeline: [],
                    },
                  ],
                  customerSpecificPricing: [],
                  customerSpecificInventory: [],
                  dateCode: '2047',
                  resources: [
                    {
                      type: 'detail',
                      uri: 'https://www.verical.com/pd/nexperia-rectifier-BAS16VY-115-3235293',
                    },
                    {
                      type: 'add_to_cart',
                      uri: 'https://www.verical.com/pd/nexperia-rectifier-BAS16VY-115-3235293',
                    },
                  ],
                  inStock: true,
                  mfrLeadTime: 0,
                  tariffFlag: false,
                  shipsFrom: 'United States of America',
                  shipsIn: 'Ships in 2 days ',
                  arrowLeadTime: '',
                  isNcnr: false,
                  isNpi: false,
                  productCode: 'BAS16VY115',
                  eccnCode: 'EAR99',
                  htsCode: '8541.10.00.80',
                  containerType: '',
                },
              ],
            },
          ],
        },
        {
          code: 'arrow.com',
          name: 'arrow.com',
          sources: [
            {
              currency: 'USD',
              sourceCd: 'EUROPE',
              displayName: 'Europe',
              sourceParts: [
                {
                  packSize: 3000,
                  minimumOrderQuantity: 3000,
                  sourcePartId: 'E02:0323_00016422',
                  Prices: {
                    resaleList: [
                      {
                        displayPrice: '0.0265',
                        price: 0.0265,
                        minQty: 3000,
                        maxQty: 8999,
                        vipPrice: true,
                      },
                      {
                        displayPrice: '0.0261',
                        price: 0.0261,
                        minQty: 9000,
                        maxQty: 999999999,
                        vipPrice: true,
                      },
                    ],
                  },
                  Availability: [
                    {
                      fohQty: 90000,
                      availabilityCd: 'INSTKEU',
                      availabilityMessage: 'In Stock',
                      pipeline: [
                        {
                          delivery: '14-MAY-2021',
                          quantity: 9000,
                        },
                      ],
                    },
                  ],
                  customerSpecificPricing: [],
                  customerSpecificInventory: [],
                  dateCode: '2103',
                  resources: [
                    {
                      type: 'detail',
                      uri: 'https://www.arrow.com/en/products/bas16vy115/nexperia',
                    },
                    {
                      type: 'add_to_cart',
                      uri: 'https://www.arrow.com/en/products/bas16vy115/nexperia',
                    },
                  ],
                  inStock: true,
                  mfrLeadTime: 16,
                  tariffFlag: false,
                  shipsFrom: 'Netherlands',
                  shipsIn: 'Ships in 3 days ',
                  arrowLeadTime: '',
                  isNcnr: false,
                  isNpi: false,
                  productCode: 'BAS16VY115',
                  eccnCode: 'EAR99',
                  htsCode: '8541.10.00.80',
                  countryOfOrigin: 'MY',
                  containerType: '',
                },
              ],
            },
            {
              currency: 'USD',
              sourceCd: 'ASIA',
              displayName: 'Asia',
              sourceParts: [
                {
                  packSize: 3000,
                  minimumOrderQuantity: 3000,
                  sourcePartId: '0893_00016422',
                  Prices: {
                    resaleList: [
                      {
                        displayPrice: '0.026',
                        price: 0.026,
                        minQty: 3000,
                        maxQty: 8999,
                        vipPrice: true,
                      },
                      {
                        displayPrice: '0.0255',
                        price: 0.0255,
                        minQty: 9000,
                        maxQty: 999999999,
                        vipPrice: true,
                      },
                    ],
                  },
                  Availability: [
                    {
                      fohQty: 72000,
                      availabilityCd: 'INSTK',
                      availabilityMessage: 'In Stock',
                      pipeline: [],
                    },
                  ],
                  customerSpecificPricing: [],
                  customerSpecificInventory: [],
                  dateCode: '2104',
                  resources: [
                    {
                      type: 'detail',
                      uri: 'https://www.arrow.com/en/products/bas16vy115/nexperia',
                    },
                    {
                      type: 'add_to_cart',
                      uri: 'https://www.arrow.com/en/products/bas16vy115/nexperia',
                    },
                  ],
                  inStock: true,
                  mfrLeadTime: 10,
                  tariffFlag: false,
                  shipsFrom: 'China',
                  shipsIn: 'Ships in 5 days ',
                  arrowLeadTime: '',
                  isNcnr: false,
                  isNpi: false,
                  productCode: 'BAS16VY115',
                  eccnCode: 'EAR99',
                  htsCode: '8541.10.00.80',
                  countryOfOrigin: 'MY',
                  containerType: '',
                },
              ],
            },
            {
              currency: 'USD',
              sourceCd: 'ACNA',
              displayName: 'Arrow Americas',
              sourceParts: [
                {
                  packSize: 3000,
                  minimumOrderQuantity: 3000,
                  sourcePartId: 'V36:1790_06513578',
                  Prices: {
                    resaleList: [
                      {
                        displayPrice: '0.0289',
                        price: 0.0289,
                        minQty: 3000,
                        maxQty: 8999,
                        vipPrice: true,
                      },
                      {
                        displayPrice: '0.0283',
                        price: 0.0283,
                        minQty: 9000,
                        maxQty: 999999999,
                        vipPrice: true,
                      },
                    ],
                  },
                  Availability: [
                    {
                      fohQty: 42000,
                      availabilityCd: 'INSTK',
                      availabilityMessage: 'In Stock',
                      pipeline: [],
                    },
                  ],
                  customerSpecificPricing: [],
                  customerSpecificInventory: [],
                  dateCode: '1933',
                  resources: [
                    {
                      type: 'detail',
                      uri: 'https://www.arrow.com/en/products/bas16vy115/nexperia',
                    },
                    {
                      type: 'add_to_cart',
                      uri: 'https://www.arrow.com/en/products/bas16vy115/nexperia',
                    },
                  ],
                  inStock: true,
                  mfrLeadTime: 16,
                  tariffFlag: false,
                  shipsFrom: 'United States of America',
                  shipsIn: 'Ships today',
                  arrowLeadTime: '',
                  isNcnr: false,
                  isNpi: false,
                  productCode: 'BAS16VY115',
                  eccnCode: 'EAR99',
                  htsCode: '8541.10.00.80',
                  countryOfOrigin: 'MY',
                  containerType: '',
                },
                {
                  packSize: 1,
                  minimumOrderQuantity: 1,
                  sourcePartId: 'V72:2272_06513578',
                  Prices: {
                    resaleList: [
                      {
                        displayPrice: '0.0658',
                        price: 0.0658,
                        minQty: 1,
                        maxQty: 9,
                        vipPrice: true,
                      },
                      {
                        displayPrice: '0.0651',
                        price: 0.0651,
                        minQty: 10,
                        maxQty: 24,
                        vipPrice: true,
                      },
                      {
                        displayPrice: '0.0548',
                        price: 0.0548,
                        minQty: 25,
                        maxQty: 99,
                        vipPrice: true,
                      },
                      {
                        displayPrice: '0.0377',
                        price: 0.0377,
                        minQty: 100,
                        maxQty: 249,
                        vipPrice: true,
                      },
                      {
                        displayPrice: '0.0352',
                        price: 0.0352,
                        minQty: 250,
                        maxQty: 499,
                        vipPrice: true,
                      },
                      {
                        displayPrice: '0.0327',
                        price: 0.0327,
                        minQty: 500,
                        maxQty: 999,
                        vipPrice: true,
                      },
                      {
                        displayPrice: '0.0301',
                        price: 0.0301,
                        minQty: 1000,
                        maxQty: 2999,
                        vipPrice: true,
                      },
                      {
                        displayPrice: '0.0295',
                        price: 0.0295,
                        minQty: 3000,
                        maxQty: 999999999,
                        vipPrice: true,
                      },
                    ],
                  },
                  Availability: [
                    {
                      fohQty: 16203,
                      availabilityCd: 'CSTRP',
                      availabilityMessage: 'Cut Strips',
                      pipeline: [],
                    },
                  ],
                  customerSpecificPricing: [],
                  customerSpecificInventory: [],
                  dateCode: '1909',
                  resources: [
                    {
                      type: 'detail',
                      uri: 'https://www.arrow.com/en/products/bas16vy115/nexperia',
                    },
                    {
                      type: 'add_to_cart',
                      uri: 'https://www.arrow.com/en/products/bas16vy115/nexperia',
                    },
                  ],
                  inStock: true,
                  mfrLeadTime: 16,
                  tariffFlag: false,
                  shipsFrom: 'United States of America',
                  shipsIn: 'Ships today',
                  arrowLeadTime: '',
                  isNcnr: false,
                  isNpi: false,
                  productCode: 'BAS16VY115',
                  eccnCode: 'EAR99',
                  htsCode: '8541.10.00.80',
                  countryOfOrigin: 'MY',
                  containerType: 'Cut Strips',
                },
              ],
            },
          ],
        },
      ],
    },
    hasDatasheet: true,
    categoryName: 'Rectifiers',
    status: 'Active',
  },
]

export default oneProduct
